package com.almutlaq.realstate.utility

object StatusConstant {

    val USER_ERROR_MSG : String = "Please enter email."
    val PASSWORD_ERROR_MSG : String = "Please enter password."
    val USER_LOGIN_ERROR_MSG : String = "Please check your email or password"
    val NEW_PASSWORD_ERROR_MSG : String = "Please enter new password."
    val RE_PASSWORD_ERROR_MSG : String = "Please enter confirm password."
    val MISMATCH_PASSWORD_ERROR_MSG : String = "The password confirmation does not match."
    val CHANGE_PASSWORD_SUCCESS_MSG : String = "The password change successfully."
    val FORGOT_PASSWORD_SUCCESS_MSG : String = "Email is not registered."
    val FORGOT_PASSWORD_FAILURE_MSG : String = "Email is not registered."
    val COMPLAIN_SUB_ERROR_MSG : String = "Please enter  subject."
    val COMPLAIN_NOTE_ERROR_MSG : String = "Please describe your notes."
    val REQUEST_NOTE_ERROR_MSG : String = "Please Describe your service notes."
    val NO_DATA_MSG : String = "No data found."
    val REQUEST_PERCENT_ERROR_MSG : String = "Please select service percentage."
    val REQUEST_LABOUNM_ERROR_MSG : String = "Please select engineer name."
    val CALL_ERROR_MSG : String = "Service close"
    var SERVER_MSG : String = ""
    val EMAIL_ERROR_MSG : String = "Please enter email id."
    val EMAIL_VALID_ERROR_MSG : String = "Please enter valid email ."
    val SLOTTIME_ERROR_MSG : String = "Choose booking requested time."
    val ACK_DATE_ERROR_MSG : String = "Please select response date."
    val ACK_SLOTTIME_ERROR_MSG : String = "Please select response time."
    val REQUEST_SUBSERVICE_TYPE_ERROR_MSG : String = "Choose Subservice Type."
    val REQUEST_T_DATE_ERROR_MSG : String = "Choose date."

    val RATING_ERROR_MSG : String = "Please give rating."
    val RATING_FEEDBACK_ERR_MSG : String = "Please enter feedback note."
    val REQUEST_DATE_ERROR_MSG : String = "Please Select reschedule date."
    val REQUEST_TIME_ERROR_MSG : String = "Please Select reschedule time."

    val ALERT : String = ""
    val SHARED_PREF = "Paylite_firebase"
    var DAY = "day"
    var INTRO = "intro"
    var FCM_TOKEN = "fcmtoken"
    var fcm_message = "FCM_MESSAGE."
    var fcm_tag = "FCM_TAG."
    var fcm_page = "FCM_PAGE"
    var fcm_booking_id = "FCM_BOOK_ID"
    var NOTIFICATION_ACTION = "DISPLAY_MESSAGE_ACTION."
    var push_notifiction = "Notification."
    var shared_prefference="Almutlaq"
    var TOKEN = "token"
    var USER_TYPE = "user_type"
    var CUSTOMER_ID = "customer_id"
    var CUSTOMER_NAME = "customer_name"
    var CUSTOMER_PROFILE_PIC = "customer_profilePic"
    var CUSTOMER_EMAIL = "customer_email"
    var CUSTOMER_PHONE = "customer_phone"
    var CUSTOMER_STREET_ADDRESS = "customer_street_address"
    var CUSTOMER_BUILDING_NO = "customer_building_no"
    var CUSTOMER_FLAT_NO ="customer_flat_no"
    var CUSTOMER_ACCOUNT_STATUS ="customer_account_status"
    var CUSTOMER_EXPIRY_DATE ="customer_Expiry_Date"
    var OFFICE_SOS = "Office_SOS"
    var PRIVATE_SOS = "Private_SOS"
    var FORCE_CHANGE_PASSWORD = "force_chng_pw"
    var WORKING_HOURS = "Working_Hours"
    final var TODAY_DAY_LINK   = "today_day"
    val wait_msg = " Please wait..."

    var INTENT_TABPOSITION : String = "tabpos"
    val INTENT_TSERVICE_BOOKINGID : String = "bookingid"
    val INTENT_TSERVICE_SERVICEID : String = "serviceid"
    val INTENT_TSERVICE_SUBSERVICE_ID : String = "subserviceid"
    val INTENT_TSERVICE_TYPE : String = "servicetype"
    val INTENT_TSERVICE_NAME : String = "servicename"
    val INTENT_TSERVICE_IMG : String = "serviceimg"
    val INTENT_TSERVICE_DATE : String = "servicedate"
    val INTENT_TSERVICE_ACK : String = "acknowledged"
    val INTENT_TSERVICE_BOOK_ACCEPT : String = "bookingaccepted"
    val INTENT_TSERVICE_ACK_SLOT_DATE : String = "ackslotdate"
    val INTENT_TSERVICE_ACK_REQ_DATE : String = "ackreqdate"
    val INTENT_TSERVICE_TENANTTIME : String = "tenanttimeslot"
    val INTENT_TSERVICE_TENANTDATE : String = "tenantdateslot"
    val INTENT_TSERVICE_CSKTIME : String = "csktimeslot"
    val INTENT_TSERVICE_BOOKNOTE : String = "bookingnote"
    val INTENT_TSERVICE_FLATNO : String = "flatno"
    val INTENT_TSERVICE_BUILDINGNO : String = "buildingno"
    val INTENT_TSERVICE_BUILDINGADDRESS : String = "buildingaddress"
    val INTENT_T_BOOKING_PERCENT : String = "bookingpercent"
    val INTENT_T_STATUS_REQUEST : String = "statusrequest"
    val INTENT_CS_BOOKING_ID : String = "bookingid"
    val INTENT_CS_HISTORY_LIST : String = "historylist"
    val INTENT_SUBSERVICE : String = "subservice"


    var statuspercent : String = "statuspercent"

    val INTENT_THANKYOU_MSG : String = "thankyoumessage"
    val INTENT_THANKYOU_MSG_TXT : String = "messagetext"

    val ACK_THANKYOU_MSG : String = "Service has been acknowledged. You will receive confirmation from Tenant soon."


}